name: Build and Release Rule-Sets

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs automatically at your specified times
  schedule:
    # 6:45 AM CST (UTC+8) is 22:45 UTC on the previous day
    - cron: "45 22 * * *"
    # 23:00 PM CST (UTC+8) is 15:00 UTC on the same day
    - cron: "0 15 * * *"

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create releases and push to a branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install requests

      - name: Run converter script to generate JSON files
        run: python convert.py

      - name: Download sing-box binary
        run: |
          LATEST_URL=$(curl -sL "https://api.github.com/repos/SagerNet/sing-box/releases/latest" | grep "browser_download_url" | grep "linux-amd64" | cut -d '"' -f 4)
          wget -q "$LATEST_URL" -O sing-box.tar.gz
          tar -xzf sing-box.tar.gz
          mv sing-box-*-linux-amd64/sing-box .
          chmod +x ./sing-box
          ./sing-box version

      - name: Compile JSON rules to SRS format
        run: |
          mkdir -p dist
          for json_file in dist/*.json; do
            srs_file="${json_file%.json}.srs"
            echo "Compiling $json_file to $srs_file..."
            ./sing-box rule-set compile "$json_file" --output "$srs_file"
          done

      - name: 🚀 Deploy SRS files to release branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: release
          force_orphan: true # Creates a clean branch history with only the latest files
          commit_message: "Update rule-sets (${{ github.sha }}) [ci skip]"

      - name: Set Release Tag and Name as Unix Timestamp
        id: set_vars
        run: |
          TIMESTAMP=$(date +%s)
          echo "RELEASE_TAG_AND_NAME=$TIMESTAMP" >> $GITHUB_ENV

      - name: 📦 Create New GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG_AND_NAME }}
          name: ${{ env.RELEASE_TAG_AND_NAME }}
          generate_release_notes: true
          files: |
            dist/*.srs
